name: flaskdemov1

services:
  flaskdemo:
    build: .
    ports:
      - "80:5000"
    volumes:
      - flaskdemo-v:/usr/src/app/data
    develop:
      watch:
        - action: sync
          path: .
          target: usr/src/app
          ignore:
            - data/
        - action: rebuild
          path: requirements.txt
volumes:
  flaskdemo-v:
    name: flaskdemo-v

